using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlaceFarmer : MonoBehaviour
{
    [SerializeField] GameObject farmer;
    [SerializeField] GameObject farmerParent;
    GameObject farmerChild;

    float gridSize = 1f; // trying to make the farmer attach to grid
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Vector2 mousePos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            // Look for closet grid cell (Part of code generated by chatgpt because couldnt find clean solution
            float x = Mathf.Round(mousePos.x / gridSize) * gridSize;
            float y = Mathf.Round(mousePos.y / gridSize) * gridSize;
            Vector2 gridPos = new Vector2(x, y);
            farmerChild = Instantiate(farmer, gridPos, Quaternion.identity);
            farmerChild.transform.parent = farmerParent.transform;
        }
    }
}
